name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    
    steps:
      # Manual Checkout
      - uses: actions/checkout@v3

      # Set up Node
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      # Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: yarn install
          build_command: npm run build-storybook
          path: storybook-static
          checkout: false
