name: Build Storybook and push to gh-pages

on:
  pull_request:
    branches:
      - main
    paths:
      - src/stories/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@master

      - name: Install all dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build-storybook-pages
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: storybook-static # The directory where your assets are generated
          TARGET_DIR: storybook
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message